HOST: http://contenthub.lostghost.com/

--- ContentHub ---
---
---

--
Class Resources
The following is a section of resources related to content classes
--
List available classes
GET /classes
< 200
< Content-Type: application/json
{ "classes": [{"id":"1234", "name":"deals", "description":"description"}, {"id":"2345", "name":"coupons", "description":"description"}] }

Create a new class
POST /classes
> Content-Type: application/json
{ "name":"deals", "description":"description" }
< 200
< Content-Type: application/json
{ "id":"1234", "name":"deals", "description":"description" }

Get a class
GET /classes/{name}
< 200
< Content-Type: application/json
{ "id":"1234", "name":"deals", "description":"description" }

